name: crud_sqflite
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.4.1
  sqflite_common_ffi: ^2.3.4+3
  path: ^1.9.0
  provider: ^6.1.2
  window_size: ^0.1.0
  desktop_window: ^0.4.2
  window_manager: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/demo/home_screen.jpeg
    - assets/demo/delete_user.jpeg
    - assets/demo/edit_user.jpeg
    - assets/demo/user_list.jpeg
